debug: false
---
spring:
  profiles:
    active: local
---
spring:
  application:
    name: spring-boot-template-service
---
spring:
  profiles: local
  cloud:
    stream:
      bindings:
        template-channel:
          contentType: application/json
          destination: com.template.dispatch
          group: template.queue
    config:
      enabled: false
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATSABASE:TEMPLATE}
      username: ${MONGO_USERNAME:overledger_test}
      password: ${MONGO_PASSWORD:overledger_test}
      authentication-database: admin
  # By default, rabbitMQ uses a topic exchange. To send messages to multiple consumers, use a 'fanout' exchange.
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASS:guest}
server:
  port: ${SERVER_PORT:8080}
logging:
  level:
    io.overledger.springboottemplate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: "*"
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    enabled-by-default: false
#  endpoint:
#    shutdown:
#      enabled: true
#    health:
#      enabled: true
#      show-details: always